# Standards: 0.11
---

# 1.7.1.3 Ensure remote login warning banner is configured properly

- name: 1.7.1.3 - Ensure remote login warning banner is configured properly
  copy:
    content: "{{ cis_remote_login_warning_banner }}"
    dest: "/etc/issue.net"
    mode: 0755
    owner: root
    group: root
  tags:
    - level-1
    - 1.7.1.3
    - not-scored
